### PR TITLE
`bunch` with `bunch`

### PR DESCRIPTION
**Pull request by tamird**
@MBerhault @bdarnell

### CODE REVIEW

**Comment by tamird** [comment]
cc @dkulchenko looks like this caused the build to blow through 4GB of ram on the Circle CI machine

**Comment by dkulchenko** [comment]
There was a recursion issue which I fixed in d21e0b0, could you try again?

**Comment by tamird** [comment]
Same thing happened on retry. It works on my machine, fwiw

**Comment by dkulchenko** [comment]
Think I know what the issue could be, will push a fix in a bit.

**Comment by dkulchenko** [comment]
Could you try again with the latest bunch master? Has some fixes in there that might prevent this.

**Comment by tamird** [comment]
That totally broke bunch.
```
$ bunch update github.com/dkulchenko/bunch
$ bunch update --save github.com/dkulchenko/bunch # this time it's running the new code
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
running vendored bin/bunch was unsuccessful
```

**Comment by tamird** [comment]
Heh, I had to `go get -u` to update the "real" bunch.

**Comment by tamird** [comment]
Hey, that fixed it.

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
