### PR TITLE
Change default port from 8080 to 26257

### PR DESCRIPTION
**Pull request by bdarnell**
See cockroachdb/cockroach#2735

### CODE REVIEW

**Comment by mberhault** [comment]
yeah, that probably won't help. bunch still tries to pull cockroachdb/cockroach/proto, which has recently been renamed to roachpb

**Comment by bdarnell** [comment]
That's just a stale link, we don't even need the proto dependency any more. We need to override the dependencies section of circle.yml because amazon broke their API (again!), and we also need to update the bunchfile. I'm working on it.

**Comment by bdarnell** [comment]
OK, fixed the dependencies and the build is green.

**Comment by mberhault** [comment]
LGTM

**Pull request merged**
