### PR TITLE
Use GCE terraform config for benchmark/sql logic/stress

### PR DESCRIPTION
**Pull request by mberhault**
This depends on https://github.com/cockroachdb/cockroach/pull/6094

### CODE REVIEW

**Comment by mberhault** [comment]
these changes + the terraform ones passed a testing run minus bad `mail` invocation on OSX.
I'm performing a real run. Results should be available in ~1h30 on the daily mailing list.

**Comment by mberhault** [comment]
ok, latest run worked just fine, see email to daily.
However, changing the env on the benchmark server failed. @dt, how can we add `gce` as a valid environment?
Here's what I got:
```
/home/marc/cockroach/src/github.com/cockroachdb/cockroach-prod/scripts/upload_benchmarks.py -e gce -r 0903b5fb8673a3df981587dbf1372a270ec7d18d -p cockroach -s http://benchmarks.dev.cockroachdb.com:80 cockroach/util/util.test.json
HTTP Error 400: BAD REQUEST
Environment gce not found
```

**Comment by mberhault** [comment]
@dt: nevermind, I dug up your instructions for the admin login. added the gce environment.

**Comment by mberhault** [comment]
@cuongdo: the tweaks for this one are mostly about key_name

**Comment by cuongdo** [comment]
totally dropped the ball on this one... sorry! LGTM

**Pull request merged**
