### PR TITLE
Single-step cluster turnup.

### PR DESCRIPTION
**Pull request by mberhault**
* add a "cockroach-initializer" null resource. Runs only once.
* remove launsh.sh in favor of supervisor

This is not to be merged yet, I still need to adapt my nightly scripts.

### CODE REVIEW

**Comment by tschottdorf** [comment]
Works like a charm. But if we're eventually going to put this into production, removing the `init` step is tricky. I just built a three node cluster and manually removed `cockroach.0` (terminating from the AWS dashboard). Of course the next invocation of `terraform apply` recreated it (presumably initializing a cluster again which would interfere with the existing one).
I can't really verify this because for some reason that new first node isn't even running ssh (suspecting that something else went wrong here).

**Comment by mberhault** [comment]
it shouldn't have re-run the null_resource, either the init or the runner. the terraform stdout should show just the instance being created

**Comment by tschottdorf** [comment]
you're right, it didn't run anything (just created an instance with nothing on it). That can't be correct?

**Comment by mberhault** [comment]
that's the problem. the null_resource thinggies don't re-run when the instance changes

**Comment by mberhault** [comment]
ok. lots more work to be done here. I'll re-open when I have the nightly runs working with supervisor

**Comment by tschottdorf** [comment]
Are you going to address that recreation issue? That seems like something actual production users would really need.

**Comment by mberhault** [comment]
yup. I started playing with the new `null_resource.triggers`, but it didn't behave as expected when using `taint`. I'll poke some more, I definitely want to get it working properly for normal failures (eg: instance dead)

**Pull request closed without merging**
